"""Константы состояний для ConversationHandler"""

# Состояния для ConversationHandler
(CHOOSING_ACTION, REGISTRATION_NAME, REGISTRATION_PHONE, REGISTRATION_ADDRESS,
 ORDER_NAME, ORDER_PHONE, ORDER_ADDRESS, ORDER_BOTTLES, ORDER_DATE, ORDER_TIME,
 RESCHEDULE_SELECT, RESCHEDULE_DATE, RESCHEDULE_TIME, ORDER_ACTION,
 EDIT_NAME, EDIT_PHONE, EDIT_ADDRESS) = range(17)

